apiVersion: v1
kind: Service
metadata:
  name: devops-assignment-2-service
spec:
  selector:
    app: devops-assignment-2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer